config/routes.rb
Rails.application.routes.draw do
  #get 'meeting/index'
  #get 'meeting/show'
  get 'users/sign_up', to: 'leads#show'
  root to: 'leads#show'
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :leads  do
    resources :meetings
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :name, :email, :phone, :status, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Email validos por favor" }, uniqueness: true
  validates :phone, length: { is: 9, message: "Poner 9 digitos del telefono,  solamente numeros" }, numericality: { only_integer: true, message: "Poner 9 digitos del telefono,  solamente numeros" }
  validates :status, presence: true

  belongs_to :user

  has_many :meetings, dependent: :destroy
  accepts_nested_attributes_for :meetings

  has_many :users, through: :meetings
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  validates :content, :summary, presence: true

  belongs_to :lead
  belongs_to :user


end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :leads, through: :meetings, dependent: :destroy

  has_many :meetings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:edit, :update, :destroy]

  def index
    @leads = Lead.all
  end

  def show
    @me = current_user
    @leads = Lead.all.order('indate') # todos ven todo
    ###############
    # ALERT, TODO, despues lo arreglo
    # Putting the variable directly into the conditions string will pass the variable to the database as-is. This means that it will be an unescaped variable directly from a user who may have malicious intent.
    # el admin puede ver todo, los usuarios solo sus leads
    #@leads = Lead.where("user_id = #{@me.id}")
    ###############
    # TODO: hacer un scope para la siguiente linea
    @meetings = Meeting.where("user_id = #{@me.id}")
    @desglose = Lead.pluck("status").tally   # si pero tally es para ruby 2.7
  end

  def new
    @lead = Lead.new
    @statuses = statuses
  end

  def edit
    @lead = Lead.find(params[:id])
  end


  def create
    @lead = Lead.new(lead_params)
    @lead.user = current_user
    @statuses = statuses
    if @lead.save
      redirect_to lead_path(@lead)
    else
      render :new
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy
    redirect_to '/'
  end

  def update
    @lead.update(lead_params)
    redirect_to root_path
  end

  private

  def lead_params
    params.require(:lead).permit(:email, :name, :phone, :status, :indate, :user)
  end

  def set_lead
    @lead = Lead.find(params[:id])
  end

  def statuses
    Status.pluck("status")
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :find_lead,  except: [ :new ]

  def index
    @meeting = Meeting.new
    @meetings = @lead.meetings
  end

  def show
    @meetings = @lead.meetings
  end

  def new
    #@meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    #weno, estas dos siguientes lineas me costo un trio de horas averiguarlas
    @meeting.lead = @lead
    @meeting.user = current_user
    #byebug

    if @meeting.save
      redirect_to lead_meetings_path(@lead)
    else
      render :new
    end
  end



  private

  def meeting_params
    params.require(:meeting).permit(:summary, :content)
  end

  def find_lead
    @lead = Lead.find(params[:lead_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aprendizaje101</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <script src="https://www.w3schools.com/lib/w3.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
<%= render 'shared/navbar' %>
<div class="px-2">
  <%= render 'shared/flashes' %>
  <%= yield %>
</div>
</body>
</html>

app/views/leads/_formlead.html.erb
<%= simple_form_for @lead , :html => { :class => 'form-horizontal' } do |l| %>

  <%= l.input :status, :collection => @statuses, selected: @statuses[0], label: false %>
  <%= l.input :name,  placeholder: 'Nombre Completo', label: false %>
  <%= l.input :email, placeholder: 'usuario@sitio.com', label: false %>
  <%= l.input :phone, placeholder: '987654321', label: false %>
  <%= l.input :indate, as: :date, start_year: Date.today.year - 5,
              end_year: Date.today.year, order: [:day, :month, :year], label: 'Fecha de ingreso'  %><br>
  <%= l.submit 'Crear prospecto',  class: 'btn button btn-primary'  %><br>


<% end %>

app/views/leads/edit.html.erb
<h1> Editar un prospecto </h1>
<%= render 'formlead', lead: @lead %>

app/views/leads/new.html.erb
<h1> Agregar un nuevo prospecto </h1>

<%= render 'formlead' %>

app/views/leads/show.html.erb
<h3>Hola <%= @me.name %>!</h3>

<div class="card-group">
      <div class="card border border-primary rounded mx-auto" style="max-width: 15rem;">
        <div class="card-body text-center">
          <h4 class="card-title">Interesados</h4>
          <h2 class="card-text"><%= @desglose["interesado"] %></h2>
        </div>
      </div>
    <div class="card border border-primary rounded mx-auto" style="max-width: 15rem;">
      <div class="card-body  text-center">
        <h4 class="card-title">Prospectos</h4>
        <h2 class="card-text"><%= @desglose["prospecto"] %></h2>
      </div>
    </div>
      <div class="card border border-primary rounded mx-auto" style="max-width: 15rem;">
        <div class="card-body text-center">
          <h4 class="card-title">Clientes</h4>
          <h2 class="card-text"><%= @desglose["cliente"] %></h2>
        </div>
      </div>
  </div>



<h4> Tablero de prospectos </h4>
<p>
  <%= link_to '➕ Agregar un prospecto', new_lead_path, title: 'Agregar prospecto'%>
</p>
<div class="table-responsive">
<table id="myTable" class="table table-borderless align-top">
  <thead class="table-dark">
  <tr>
    <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(1)')" style="cursor:pointer">Email <i class="fa fa-sort" style="font-size:13px;"></i></th>
    <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(2)')" style="cursor:pointer">Nombre <i class="fa fa-sort" style="font-size:13px;"></i></th>
    <th >Celular</th>
    <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(4)')" style="cursor:pointer">Estado <i class="fa fa-sort" style="font-size:13px;"></i></th>
    <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(5)')" style="cursor:pointer">Ingresante <i class="fa fa-sort" style="font-size:13px;"></i></th>
    <th onclick="w3.sortHTML('#myTable','.item', 'td:nth-child(6)')" style="cursor:pointer">Fecha <i class="fa fa-sort" style="font-size:13px;"></i></th>
    <th>Reus</th>
    <th>Opciones</th>
  </tr>
  </thead>
  <tbody>
  <% @leads.each do |lead| %>
    <tr class="item <%= cycle('even', 'odd') -%>">
      <td><%= lead.email %></td>
      <td><%= lead.name %></td>
      <td><%= lead.phone %></td>
      <td><%= lead.status %></td>
      <td><%= User.find(lead.user_id).name %></td>
      <td><%= lead.indate %></td>
      <td>
        <span class="fs-5"><%= link_to "#{lead.meetings.count}💬", lead_meetings_path(lead), title: 'Numero de juntas/llamadas' %></span></td>
      <td>
        <span class="fs-5">
        <%= link_to "📝", edit_lead_path(lead), title: 'Editar prospecto' %>
        <%= link_to "🗑️", lead_path(lead), title: 'Eliminar prospecto', method: :delete, data: { confirm: "Esta seguro? Se eliminaran todas las conversaciones de este prospecto"} %>
        </span>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>
</div>

</body>
</html>

app/views/meetings/_formmeeting.html.erb
<%= simple_form_for [ @lead, @meeting ] do |m| %>
  <%= m.input :summary %>
  <%= m.input :content, as: :text, input_html: {rows: 10, cols: 40} %>
  <%= m.submit "Subir conversacion", class: "btn btn-primary" %>
<% end %>

app/views/meetings/index.html.erb
<h4>  <%= link_to "Prospectos", root_path %></h4>
<p></p>
<% unless @meetings.count == 0 %>
  <h4>Conversaciones con el prospecto <%= @lead.name %></h4>
  <div class="table-responsive">

  <table  class="table table-borderless align-top">
    <thead class="table-dark">
    <tr>
      <th>Resumen</th>
      <th>Detalle</th>
      <th>Fecha ingreso</th>
    </tr>
    </thead>
    <tbody>

    <% @meetings.each do |meet| %>
      <tr class="<%= cycle('even', 'odd') -%>">
        <td><%= meet.summary %></td>
        <td><%= meet.content %></td>
        <td><%= meet.created_at.in_time_zone('America/Santiago').strftime("%Y-%m-%d") %></td>
      </tr>


    <% end %>
    </tbody>

  </table>
  </div>
<% else %>
  <p>No hay conversaciones!</p>
<% end %>
<h4>Nueva conversacion</h4>
<%= render('formmeeting')
%>

app/views/meetings/new.html.erb
<%= render('formmeeting') %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="w3-panel w3-green w3-display-container w3-card-4">
  <span onclick="this.parentElement.style.display='none'"
        class="w3-button w3-small w3-display-topright">&times;</span>
    <p>    <%= notice %></p>
  </div>
<% end %>
<% if alert %>
  <div class="w3-panel w3-yellow w3-display-container w3-card-4">
  <span onclick="this.parentElement.style.display='none'"
        class="w3-button w3-small w3-display-topright">&times;</span>
    <p>    <%= alert %></p>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark text-white navbar-expand-sm">

    <% if user_signed_in? %>
      <div class="p-2 flex-grow-1 bd-highlight"><%= link_to "Aprendizaje101 CRM Intraweb", root_path %></div>
      <div class="p-2 bd-highlight">Sesion iniciada: <strong><%= current_user.email %></strong></div>
      <div class="p-2 bd-highlight"><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></div>
    <% else %>
    <div class="p-2 bd-highlight"><%= link_to "Iniciar sesion", new_user_session_path, class: "nav-link" %></div>
      <% end %>

</nav>